version: '3'
services:
  frontend:
    build: .
    network_mode: 'host'
    stdin_open: true
    ports:
    - 3000:3000
    volumes:
    - ./:/app
  backend:
    build: ../backend/
    network_mode: 'host'
    ports:
      - 5000:5000
    volumes:
      - ../backend/:/app
