version: '3'
services:
  frontend:
    build: frontend
    ports:
    - 8080:80
    volumes:
    - ./conf/default.conf:/etc/nginx/conf.d/default.conf:ro
    - ./conf/nginx.conf:/etc/nginx/nginx.conf:ro
    links:
      - backend
    depends_on:
      - backend
  backend:
    build: backend
    ports:
      - 127.0.0.1:5000:5000
    volumes:
      - ./data/:/app/data
    command: yarn start
